Adding security feature

In [25]:
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import ast
import math
import pickle
import seaborn as sns; 

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, KFold,GridSearchCV
from sklearn.metrics import confusion_matrix, precision_score, recall_score, auc, accuracy_score, roc_auc_score, roc_curve, f1_score, classification_report

In [2]:
df1 = pd.read_csv(r"C:\Users\Amodini\Documents\MSSI\III sem\CIP\project\2023-11-05_12-56-40-537865_results_Success_security.csv", delimiter=',')
df1.head()

,total_time,timedelta,simulation_status,World.PrimaryBattleship.x,World.PrimaryBattleship.y,World.PrimaryBattleship.actions,World.PrimaryBattleship.heading,World.PrimaryBattleship.desired_heading,World.PrimaryBattleship.option_port,World.PrimaryBattleship.option_starboard,...,World.AircraftCarrier.Navigation.waypoints,World.AircraftCarrier.Navigation.completed_waypoints,World.AircraftCarrier.RadarSonar.collision_warning,World.AircraftCarrier.RadarSonar.collision_event,World.AircraftCarrier.RadarSonar.radar_geometry,World.AircraftCarrier.RadarSonar.radar_objects,World.AircraftCarrier.RadarSonar.warning_objects,World.AircraftCarrier.RadarSonar.collision_objects,World.AircraftCarrier.RadarSonar.transformed_geometry,Security AI
0,0.0,0.0,Unknown,2200.0,1200.0,NaN,0.0,0.0,360.0,0.0,...,"[[3000, 3000], [3468, 746]]",[],False,False,"[(1900.0, 500.0), (1892.3306535155825, 353.660...",[],[],[],"[(658.0, 510.5), (658.0, 484.5), (604.0, 477.5...",1
1,0.5,0.5,Unknown,2200.0,1200.0,Moving,0.0,0.0,360.0,0.0,...,"[[3000, 3000], [3468, 746]]",[],False,False,"[(1900.0, 500.0), (1892.3306535155825, 353.660...",[],[],[],"[(658.0, 510.5), (658.0, 484.5), (604.0, 477.5...",1
2,1.0,0.5,Unknown,2205.0,1200.0,"Moving,Turning",0.0,0.0,360.0,0.0,...,"[[3000, 3000], [3468, 746]]",[],False,False,"[(1900.0, 500.0), (1892.3306535155825, 353.660...",[],[],[],"[(658.0, 510.5), (658.0, 484.5), (604.0, 477.5...",1
3,1.5,0.5,Unknown,2210.0,1200.0,"Moving,Turning",0.0,0.0,360.0,0.0,...,"[[3000, 3000], [3468, 746]]",[],False,False,"[(1901.5, 500.0), (1893.8306535155825, 353.660...",[],[],[],"[(659.5, 510.5), (659.5, 484.5), (605.5, 477.5...",1
4,2.0,0.5,Unknown,2215.0,1200.0,"Moving,Turning",0.0,0.0,360.0,0.0,...,"[[3000, 3000], [3468, 746]]",[],False,False,"[(1903.0, 500.0), (1895.3306535155825, 353.660...",[],[],[],"[(661.0, 510.5), (661.0, 484.5), (607.0, 477.5...",1

In [3]:
df2 = pd.read_csv(r"C:\Users\Amodini\Documents\MSSI\III sem\CIP\project\2023-11-05_20-26-15-229160_results_Failure.csv", delimiter=',')

In [4]:
df_nav = pd.concat([df1, df2], ignore_index=True)

In [5]:
columns_to_select = ['World.PrimaryBattleship.x', 'World.PrimaryBattleship.y',
       'World.PrimaryBattleship.actions', 'World.PrimaryBattleship.heading',
       'World.PrimaryBattleship.desired_heading',
       'World.PrimaryBattleship.option_port',
       'World.PrimaryBattleship.option_starboard',
       'World.PrimaryBattleship.chosen_direction','World.PrimaryBattleship.out_of_bounds', 
       'World.PrimaryBattleship.Navigation.waypoints','World.PrimaryBattleship.RadarSonar.collision_warning',
       'World.PrimaryBattleship.RadarSonar.collision_event','World.AircraftCarrier.x',
       'World.AircraftCarrier.y','World.PrimaryBattleship.RadarSonar.radar_objects',
       'World.AircraftCarrier.current_speed', 'World.AircraftCarrier.Engine.desired_speed','Security AI']
df_new = df_nav[columns_to_select].copy()

In [6]:
df_new.head()

,World.PrimaryBattleship.x,World.PrimaryBattleship.y,World.PrimaryBattleship.actions,World.PrimaryBattleship.heading,World.PrimaryBattleship.desired_heading,World.PrimaryBattleship.option_port,World.PrimaryBattleship.option_starboard,World.PrimaryBattleship.chosen_direction,World.PrimaryBattleship.out_of_bounds,World.PrimaryBattleship.Navigation.waypoints,World.PrimaryBattleship.RadarSonar.collision_warning,World.PrimaryBattleship.RadarSonar.collision_event,World.AircraftCarrier.x,World.AircraftCarrier.y,World.PrimaryBattleship.RadarSonar.radar_objects,World.AircraftCarrier.current_speed,World.AircraftCarrier.Engine.desired_speed,Security AI
0,2200.0,1200.0,NaN,0.0,0.0,360.0,0.0,NaN,False,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",False,False,500.0,500.0,[],3.00,15,1
1,2200.0,1200.0,Moving,0.0,0.0,360.0,0.0,starboard,False,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",False,False,500.0,500.0,"[[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...",3.25,15,1
2,2205.0,1200.0,"Moving,Turning",0.0,0.0,360.0,0.0,starboard,False,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",False,False,501.5,500.0,"[[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...",3.50,15,1
3,2210.0,1200.0,"Moving,Turning",0.0,0.0,360.0,0.0,starboard,False,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",False,False,503.0,500.0,"[[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...",3.75,15,1
4,2215.0,1200.0,"Moving,Turning",0.0,0.0,360.0,0.0,starboard,False,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",False,False,504.5,500.0,"[[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...",4.00,15,1

Feature extraction

In [7]:
dest_coordinates = df_new['World.PrimaryBattleship.Navigation.waypoints'][0]
dest_coordinates_list = ast.literal_eval(dest_coordinates)

In [8]:
def calc_distance_from_dest(x,y,point):
    dx = x - point[0]
    dy = y - point[1]
    return math.sqrt(dx**2 + dy**2)

for i, point in enumerate(dest_coordinates_list):
    df_new[f'distance_to_point_{i + 1}'] = df_new.apply(lambda row: calc_distance_from_dest(row['World.PrimaryBattleship.x'], row['World.PrimaryBattleship.y'], point), axis=1)

In [9]:

df_new['distance_from_airplane'] = df_new.apply(lambda row: calc_distance_from_dest(row['World.PrimaryBattleship.x'], row['World.PrimaryBattleship.y'], (row['World.AircraftCarrier.x'], row['World.AircraftCarrier.y'])), axis=1)

In [10]:
df_new.columns

Index(['World.PrimaryBattleship.x', 'World.PrimaryBattleship.y',
       'World.PrimaryBattleship.actions', 'World.PrimaryBattleship.heading',
       'World.PrimaryBattleship.desired_heading',
       'World.PrimaryBattleship.option_port',
       'World.PrimaryBattleship.option_starboard',
       'World.PrimaryBattleship.chosen_direction',
       'World.PrimaryBattleship.out_of_bounds',
       'World.PrimaryBattleship.Navigation.waypoints',
       'World.PrimaryBattleship.RadarSonar.collision_warning',
       'World.PrimaryBattleship.RadarSonar.collision_event',
       'World.AircraftCarrier.x', 'World.AircraftCarrier.y',
       'World.PrimaryBattleship.RadarSonar.radar_objects',
       'World.AircraftCarrier.current_speed',
       'World.AircraftCarrier.Engine.desired_speed', 'Security AI',
       'distance_to_point_1', 'distance_to_point_2', 'distance_to_point_3',
       'distance_to_point_4', 'distance_from_airplane'],
      dtype='object')

In [11]:
df_new['World.PrimaryBattleship.RadarSonar.radar_objects'] = df_new['World.PrimaryBattleship.RadarSonar.radar_objects'].apply(ast.literal_eval)

In [113]:
df_new['World.PrimaryBattleship.RadarSonar.radar_objects']

0                                                      []
1       [[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...
2       [[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...
3       [[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...
4       [[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...
                              ...
7399    [[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...
7400    [[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...
7401    [[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...
7402    [[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...
7403    [[(2270.0, 440.0), (2365.0, 350.0), (2260.0, 3...
Name: World.PrimaryBattleship.RadarSonar.radar_objects, Length: 7404, dtype: object

In [12]:
def calculate_distance(ship_x, ship_y, radar_objects):
    distances = []
    for radar_point in radar_objects:
        if len(radar_point) > 0:
            distances.extend([np.sqrt((ship_x - x)**2 + (ship_y - y)**2) for x, y in radar_point])
    return distances[:4]

df_new[['distance_to_radar_obj_1', 'distance_to_radar_obj_2', 'distance_to_radar_obj_3', 'distance_to_radar_obj_4']] = df_new.apply(
    lambda row: pd.Series(calculate_distance(row['World.PrimaryBattleship.x'], row['World.PrimaryBattleship.y'], row['World.PrimaryBattleship.RadarSonar.radar_objects'])),
    axis=1
)
df_new[['distance_to_radar_obj_1', 'distance_to_radar_obj_2', 'distance_to_radar_obj_3', 'distance_to_radar_obj_4']] = df_new[['distance_to_radar_obj_1', 'distance_to_radar_obj_2', 'distance_to_radar_obj_3', 'distance_to_radar_obj_4']].fillna(0)

C:\Users\Amodini\AppData\Local\Temp\ipykernel_27976\455780473.py:9: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  lambda row: pd.Series(calculate_distance(row['World.PrimaryBattleship.x'], row['World.PrimaryBattleship.y'], row['World.PrimaryBattleship.RadarSonar.radar_objects'])),

In [13]:
df_new = pd.get_dummies(df_new, columns=['World.PrimaryBattleship.actions'], prefix=['action'])

In [14]:
df_new = pd.get_dummies(df_new, columns=['World.PrimaryBattleship.chosen_direction'], prefix=['direction'])

In [15]:
df_new['World.PrimaryBattleship.RadarSonar.collision_warning'] = df_new['World.PrimaryBattleship.RadarSonar.collision_warning'].astype(int)

In [16]:
df_new['World.PrimaryBattleship.RadarSonar.collision_event'] = df_new['World.PrimaryBattleship.RadarSonar.collision_event'].astype(int)

In [17]:
df_new['World.PrimaryBattleship.out_of_bounds'] = df_new['World.PrimaryBattleship.out_of_bounds'].astype(int)

In [119]:
df_new.head()

,World.PrimaryBattleship.x,World.PrimaryBattleship.y,World.PrimaryBattleship.heading,World.PrimaryBattleship.desired_heading,World.PrimaryBattleship.option_port,World.PrimaryBattleship.option_starboard,World.PrimaryBattleship.chosen_direction,World.PrimaryBattleship.out_of_bounds,World.PrimaryBattleship.Navigation.waypoints,World.PrimaryBattleship.RadarSonar.collision_warning,...,distance_to_point_2,distance_to_point_3,distance_to_point_4,distance_from_airplane,distance_to_radar_obj_1,distance_to_radar_obj_2,distance_to_radar_obj_3,distance_to_radar_obj_4,action_Moving,"action_Moving,Turning"
0,2200.0,1200.0,0.0,0.0,360.0,0.0,NaN,0,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",0,...,282.842712,412.310563,70.710678,1838.477631,0.000000,0.000000,0.000000,0.000000,0,0
1,2200.0,1200.0,0.0,0.0,360.0,0.0,starboard,0,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",0,...,282.842712,412.310563,70.710678,1838.477631,763.216876,865.866618,882.043083,763.216876,1,0
2,2205.0,1200.0,0.0,0.0,360.0,0.0,starboard,0,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",0,...,279.329554,413.551690,74.330344,1841.714487,762.774541,864.927743,881.717075,762.774541,0,1
3,2210.0,1200.0,0.0,0.0,360.0,0.0,starboard,0,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",0,...,275.862284,414.849370,78.102497,1844.952303,762.364742,864.016782,881.419310,762.364742,0,1
4,2215.0,1200.0,0.0,0.0,360.0,0.0,starboard,0,"[[3200, 1200], [2400, 1400], [2100, 1600], [21...",0,...,272.442655,416.203075,82.006097,1848.191075,761.987533,863.133825,881.149817,761.987533,0,1

In [18]:
y1 = df_new['World.PrimaryBattleship.heading']

In [19]:
y2 = df_new['World.AircraftCarrier.current_speed']

In [20]:
columns_to_drop = ['World.PrimaryBattleship.heading','World.PrimaryBattleship.Navigation.waypoints','World.AircraftCarrier.x', 'World.AircraftCarrier.y','World.PrimaryBattleship.RadarSonar.radar_objects','World.AircraftCarrier.current_speed']
df_new = df_new.drop(columns=columns_to_drop)

In [21]:
df_new.columns

Index(['World.PrimaryBattleship.x', 'World.PrimaryBattleship.y',
       'World.PrimaryBattleship.desired_heading',
       'World.PrimaryBattleship.option_port',
       'World.PrimaryBattleship.option_starboard',
       'World.PrimaryBattleship.out_of_bounds',
       'World.PrimaryBattleship.RadarSonar.collision_warning',
       'World.PrimaryBattleship.RadarSonar.collision_event',
       'World.AircraftCarrier.Engine.desired_speed', 'Security AI',
       'distance_to_point_1', 'distance_to_point_2', 'distance_to_point_3',
       'distance_to_point_4', 'distance_from_airplane',
       'distance_to_radar_obj_1', 'distance_to_radar_obj_2',
       'distance_to_radar_obj_3', 'distance_to_radar_obj_4', 'action_Moving',
       'action_Moving,Turning', 'direction_port', 'direction_starboard'],
      dtype='object')

In [22]:
df_new.head()

,World.PrimaryBattleship.x,World.PrimaryBattleship.y,World.PrimaryBattleship.desired_heading,World.PrimaryBattleship.option_port,World.PrimaryBattleship.option_starboard,World.PrimaryBattleship.out_of_bounds,World.PrimaryBattleship.RadarSonar.collision_warning,World.PrimaryBattleship.RadarSonar.collision_event,World.AircraftCarrier.Engine.desired_speed,Security AI,...,distance_to_point_4,distance_from_airplane,distance_to_radar_obj_1,distance_to_radar_obj_2,distance_to_radar_obj_3,distance_to_radar_obj_4,action_Moving,"action_Moving,Turning",direction_port,direction_starboard
0,2200.0,1200.0,0.0,360.0,0.0,0,0,0,15,1,...,70.710678,1838.477631,0.000000,0.000000,0.000000,0.000000,0,0,0,0
1,2200.0,1200.0,0.0,360.0,0.0,0,0,0,15,1,...,70.710678,1838.477631,763.216876,865.866618,882.043083,763.216876,1,0,0,1
2,2205.0,1200.0,0.0,360.0,0.0,0,0,0,15,1,...,74.330344,1841.714487,762.774541,864.927743,881.717075,762.774541,0,1,0,1
3,2210.0,1200.0,0.0,360.0,0.0,0,0,0,15,1,...,78.102497,1844.952303,762.364742,864.016782,881.419310,762.364742,0,1,0,1
4,2215.0,1200.0,0.0,360.0,0.0,0,0,0,15,1,...,82.006097,1848.191075,761.987533,863.133825,881.149817,761.987533,0,1,0,1

Training using Decision Tree

In [23]:
#for World.PrimaryBattleship.heading
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Assuming you have a target variable 'y' for regression

# Split the data into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(df_new, y1, test_size=0.2, random_state=42)

# Create a decision tree regressor
regressor_heading = DecisionTreeRegressor()

# Fit the model on the training data
regressor_heading.fit(X_train, y_train)

# Make predictions on the test set
y_pred_heading = regressor_heading.predict(X_test)

# Calculate the mean squared error (MSE) to evaluate the model's performance
mse = mean_squared_error(y_test, y_pred_heading)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.10129174162074697

In [24]:
comparison_df_heading = pd.DataFrame({'Actual (y_test)': y_test, 'Predicted (y_pred)': y_pred_heading})
comparison_df_heading.head(20)

      Actual (y_test)  Predicted (y_pred)
4366        20.219715           20.219715
3197       158.125958          158.625958
4367        20.720248           20.720248
5014      -137.891432         -137.891432
554        176.237986          175.737986
6458       -58.232646          -58.232646
4693      -176.262014         -176.262014
3770       -78.094537          -77.594539
6046        95.191919           96.196432
263         30.736947           30.736947
2316       -67.232621          -67.232621
3176       168.625958          168.625958
5776      -158.284793         -158.513033
3071      -138.874020         -138.374019
6398       -88.232481          -88.232481
5347        56.215127           55.715129
3815       -55.594603          -56.094602
1737       159.215207          159.215207
7280       178.625959          178.625959
1979       124.886623          125.368047

In [30]:
with open('nav_ai_heading.pkl', 'wb') as file:
    pickle.dump(regressor_heading, file)

In [32]:
with open('nav_ai_heading.pkl', 'rb') as file:
    test_model_heading = pickle.load(file)

y_pred_heading = test_model_heading.predict(X_test)

# Calculate the mean squared error (MSE) to evaluate the model's performance
mse = mean_squared_error(y_test, y_pred_heading)
print("Mean Squared Error:", mse)
comparison_df_heading = pd.DataFrame({'Actual (y_test)': y_test, 'Predicted (y_pred)': y_pred_heading})
comparison_df_heading.head(5)

Mean Squared Error: 0.10129174162074697

      Actual (y_test)  Predicted (y_pred)
4366        20.219715           20.219715
3197       158.125958          158.625958
4367        20.720248           20.720248
5014      -137.891432         -137.891432
554        176.237986          175.737986

In [33]:
#prediction for speed 
X_train, X_test, y_train, y_test = train_test_split(df_new, y2, test_size=0.2, random_state=42)
regressor_speed = DecisionTreeRegressor()

# Fit the model on the training data
regressor_speed.fit(X_train, y_train)

# Make predictions on the test set
y_pred_speed = regressor_speed.predict(X_test)

# Calculate the mean squared error (MSE) to evaluate the model's performance
mse = mean_squared_error(y_test, y_pred_speed)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.009284267386900743

In [35]:
with open('nav_ai_speed.pkl', 'wb') as file:
    pickle.dump(regressor_speed, file)

In [36]:
with open('nav_ai_speed.pkl', 'rb') as file:
    test_model_speed = pickle.load(file)

y_pred_speed = test_model_speed.predict(X_test)

# Calculate the mean squared error (MSE) to evaluate the model's performance
mse = mean_squared_error(y_test, y_pred_speed)
print("Mean Squared Error:", mse)
comparison_df_heading = pd.DataFrame({'Actual (y_test)': y_test, 'Predicted (y_pred)': y_pred_speed})
comparison_df_heading.head(5)

Mean Squared Error: 0.009284267386900743

      Actual (y_test)  Predicted (y_pred)
4366             15.0                15.0
3197             15.0                15.0
4367             15.0                15.0
5014             15.0                15.0
554              15.0                15.0

In [88]:
zero_speed_mask = (comparison_df_speed['Actual (y_test)'] == 0) | (comparison_df_speed['Predicted (y_pred)'] == 0)
zero_speed_values = comparison_df_speed[zero_speed_mask]
print(zero_speed_values)

      Actual (y_test)  Predicted (y_pred)
3176              0.0                 0.0
4471              0.0                 0.0
5199              0.0                 0.0
6048              0.0                 0.0
1078              0.0                 0.0
2388              0.0                 0.0
3574              0.0                 0.0
3265              0.0                 0.0
1244              0.0                 0.0
6418              0.0                 0.0
4567              0.0                 0.0
4512              0.0                 0.0
3053              0.0                 0.0
3907              0.0                 0.0
4305              0.0                 0.0
3312              0.0                 0.0
4457              0.0                 0.0
6174              0.0                 0.0

Training with Random Forest

In [89]:
X_train, X_test, y_train, y_test = train_test_split(df_new, y1, test_size=0.2, random_state=42)
rf_regressor_heading = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf_regressor_heading.fit(X_train, y_train)

# Make predictions on the test set
y_pred_heading = rf_regressor_heading.predict(X_test)
mse = mean_squared_error(y_test, y_pred_heading)
print("Mean Squared Error on Test Set:", mse)

Mean Squared Error on Test Set: 11.48742099773472

In [90]:
comparison_rf_heading = pd.DataFrame({'Actual (y_test)': y_test, 'Predicted (y_pred)': y_pred_heading})

In [91]:
comparison_rf_heading.head(20)

      Actual (y_test)  Predicted (y_pred)
4366        20.219715           20.316035
3197       158.125958          158.195958
4367        20.720248           20.765736
5014      -137.891432         -137.738105
554        176.237986          176.062986
6458       -58.232646          -58.258656
4693      -176.262014         -176.252014
3770       -78.094537          -77.788679
6046        95.191919           95.040099
263         30.736947           30.917023
2316       -67.232621          -67.262621
3176       168.625958          168.575958
5776      -158.284793         -158.382663
3071      -138.874020         -138.779020
6398       -88.232481          -88.357479
5347        56.215127           56.320127
3815       -55.594603          -55.407062
1737       159.215207          159.210323
7280       178.625959          178.590959
1979       124.886623          124.790398

In [92]:
X_train, X_test, y_train, y_test = train_test_split(df_new, y2, test_size=0.2, random_state=42)
rf_regressor_speed = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf_regressor_speed.fit(X_train, y_train)

# Make predictions on the test set
y_pred_speed = rf_regressor_speed.predict(X_test)
mse = mean_squared_error(y_test, y_pred_speed)
print("Mean Squared Error on Test Set:", mse)

Mean Squared Error on Test Set: 0.0065205982218455695

In [93]:
comparison_rf_speed = pd.DataFrame({'Actual (y_test)': y_test, 'Predicted (y_pred)': y_pred_speed})

In [94]:
comparison_rf_speed.head(10)

      Actual (y_test)  Predicted (y_pred)
4366             15.0                15.0
3197             15.0                15.0
4367             15.0                15.0
5014             15.0                15.0
554              15.0                15.0
6458             15.0                15.0
4693             15.0                15.0
3770             15.0                15.0
6046             15.0                15.0
263              15.0                15.0

Hyperparameter tuning for Decision Tree since DT giving better results

In [95]:
dt_regressor = DecisionTreeRegressor()
param_grid = {
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(dt_regressor, param_grid, cv=5, scoring='neg_mean_squared_error', verbose=1)

X_train, X_test, y_train, y_test = train_test_split(df_new, y1, test_size=0.2, random_state=42)
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
print(f"Best Hyperparameters: {best_params}")

Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Hyperparameters: {'max_depth': 30, 'min_samples_leaf': 4, 'min_samples_split': 5}

In [96]:
best_model = grid_search.best_estimator_
y_pred_heading = best_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred_heading)
print(f"Mean Squared Error on Test Set: {mse}")

Mean Squared Error on Test Set: 11.607414466687153

In [97]:
comparison_df = pd.DataFrame({'Actual (y_test)': y_test, 'Predicted (y_pred)': y_pred_heading})

In [98]:
comparison_df.head(20)

      Actual (y_test)  Predicted (y_pred)
4366        20.219715           20.846162
3197       158.125958          159.292625
4367        20.720248           20.846162
5014      -137.891432         -138.072921
554        176.237986          176.237986
6458       -58.232646          -57.777428
4693      -176.262014         -175.662014
3770       -78.094537          -78.844533
6046        95.191919           99.954538
263         30.736947           29.521546
2316       -67.232621          -67.322187
3176       168.625958          169.054530
5776      -158.284793         -158.284793
3071      -138.874020         -138.124019
6398       -88.232481          -88.532477
5347        56.215127           56.786553
3815       -55.594603          -56.163626
1737       159.215207          159.450005
7280       178.625959          178.911674
1979       124.886623          124.898591

In [99]:
X_train, X_test, y_train, y_test = train_test_split(df_new, y2, test_size=0.2, random_state=42)
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
print(f"Best Hyperparameters: {best_params}")

Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Hyperparameters: {'max_depth': 30, 'min_samples_leaf': 1, 'min_samples_split': 2}

In [100]:
best_model = grid_search.best_estimator_
y_pred_speed = best_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred_speed)
print(f"Mean Squared Error on Test Set: {mse}")

Mean Squared Error on Test Set: 0.0033338960162052666

In [102]:
comparison_df_speed = pd.DataFrame({'Actual (y_test)': y_test, 'Predicted (y_pred)': y_pred_speed})
comparison_df_speed.head(10)

      Actual (y_test)  Predicted (y_pred)
4366             15.0                15.0
3197             15.0                15.0
4367             15.0                15.0
5014             15.0                15.0
554              15.0                15.0
6458             15.0                15.0
4693             15.0                15.0
3770             15.0                15.0
6046             15.0                15.0
263              15.0                15.0

In [65]:
feature_importances = regressor.feature_importances_

# Get feature names (assuming X_train is a DataFrame)
feature_names = X_train.columns

# Get the indices of the top 5 features
top5_indices = np.argsort(feature_importances)[::-1][:5]

# Print the top 5 important feature names
for i, idx in enumerate(top5_indices):
    feature_name = feature_names[idx]
    feature_score = feature_importances[idx]
    print(f"{i+1}. {feature_name}: {feature_score:.4f}")

1. World.PrimaryBattleship.desired_heading: 0.3680
2. distance_to_point_1: 0.1435
3. World.PrimaryBattleship.option_port: 0.1182
4. World.PrimaryBattleship.x: 0.1161
5. World.PrimaryBattleship.option_starboard: 0.1108